newrelic/nrdot-collector-releases

.github/workflows/ci-goreleaser.yml, .github/workflows/ci-prerelease.yml, .github/workflows/scripts/gh_publisher.sh, .github/workflows/scripts/set_version.sh, .goreleaser.yaml
This PR will add:
- prerelease workflow for building packages
=> added packaging pipeline for pre-release

.github/workflows/ci-prerelease.yml, .github/workflows/component_molecule_packaging.yml, .github/workflows/component_publish.yml, .github/workflows/molecule_packaging_tag.yml, .goreleaser.yaml, configs/nr-otel-collector.yaml
Execution example: https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/4042601422
=> NR-78042: add packaging tests

.gitignore, test/terraform/fargate/main.tf, test/terraform/fargate/vars.tf
=> NR-81894: feat: add ecs cluster testing infrastructure

distributions/nr-otel-collector/manifest.yaml
Remove not needed processors and update other components to last release
=> Remove not needed processors and update other components to last release (NR-109507)

.github/workflows/canaries_on_demand.yml, .github/workflows/ci-prerelease.yml, .github/workflows/ci-release.yml, .github/workflows/component_canaries.yml, .github/workflows/component_molecule_packaging.yml, .github/workflows/component_provision_packaging.yml, .github/workflows/component_publish.yml, .github/workflows/molecule_packaging_tag.yml, .github/workflows/packaging_tests_on_demand.yml, distributions/nr-otel-collector/upload-schema-linux-rpm.yml, test/packaging/ansible/installation-pinned.yaml, test/packaging/ansible/requirements.yml, test/packaging/ansible/test.yaml, test/packaging/ansible/uninstallation.yaml, test/packaging/ansible/upgrade.yaml, test/provision/terraform/caos-linux.auto.tfvars.dist, test/provision/terraform/requirements.yml, tools/aws_logs.sh
- NR-109510 Replace AL2022 with AL2023
- NR-109510 Reduce test platforms
- NR-109510 Parameterize version
- style: remove commented-out fields
=> NR-109510 NRDOT prod package publishing pipeline

distributions/nr-otel-collector/manifest.yaml, test/README.md
Add filelogreceiver and update other components to last release 0.77.0
=> Add filelogreceiver and update other components to last release (NR-109507)

distributions/nr-otel-collector/THIRD_PARTY_NOTICES.md, distributions/nr-otel-collector/manifest.yaml
=> Add k8s attributes processor (NR-116487)

.github/workflows/component_canaries.yml, .github/workflows/component_canary_alerts.yml, .github/workflows/component_canary_alerts_delete.yml
- ci: checkout code before running script
- ci: update checkout action for canary alerts
=> checkout code for canaries

distributions/nr-otel-collector/THIRD_PARTY_NOTICES.md, distributions/nr-otel-collector/manifest.yaml
This Pr adds statsd and docker receivers to nrdot
=> feat(dockerStatReceiver): add docker and statsd receivers to nrdot

.github/workflows/ci-prerelease.yml, .github/workflows/component_molecule_packaging.yml, distributions/nr-otel-collector/upload-schema-linux-deb.yml, test/provision/terraform/caos-linux.auto.tfvars.dist
=> NR-144355: add support for Debian 12

distributions/nr-otel-collector/THIRD_PARTY_NOTICES.md, distributions/nr-otel-collector/manifest.yaml
This PR adds the redis receiver to NRDOT
=> NR-147983: add redis receiver to nrdot

distributions/nr-otel-collector/THIRD_PARTY_NOTICES.md, distributions/nr-otel-collector/manifest.yaml
This PR adds the apm processor and connectors that were created in this [repo](https://github.com/newrelic/opentelemetry-collector-components). cc @sdaubin @alanwest
=> feat: add apm processor and receiver to NRDOT

.github/workflows/security.yml
removing notification after ownership transfer. Feel free to replace this with the current team webhook
=> chore: remove CAOS slack notification

.github/workflows/repolinter.yml
Upgrading actions and api call, hoping this helps address failures.
=> chore: Upgrading repolinter workflow

.github/workflows/component_terraform.yml, .github/workflows/debug_terraform.yml
Secret defs were missing from the previous pr
=> fix: Add missing secret def

test/terraform/permanent/outputs.tf
Adding an output so we can capture the repo url for subsequent tasks.
=> feat: Add TF output for ecr url

.goreleaser-nightly.yaml, test/terraform/permanent/main.tf
- Publish nightly artifacts to nightly folder
=> ci: publish nightly artifacts to dedicated folder

test/e2e/util/spec/on_host.go
Adding conditions that are directly related to queries in the host ui.
=> chore: Adding conditions to host ui validation

distributions/nrdot-collector-k8s/README.md, distributions/nrdot-collector-k8s/sync-configs.sh
- Add some more user-friendly documentation on differences between distro and helm chart for k8s distro
=> docs: document difference between helm and distro

.github/workflows/terraform.yaml
=> fix: variable type in workflow

test/e2e/util/assert/nr_metric_assertion.go
- The old logic was flawed (didn't retry the actual request and didn't sleep), just re-checked the response
=> fix: properly retry assertions

.goreleaser.yaml
Configure changelog for release notes
=> ci: Conventional commit changelog formatting

test/e2e/util/spec/test_case_spec.go
- fixes [nightly error](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13569448551/job/37932129773#step:4:27)
=> ci: initialize map to avoid NPE

.github/workflows/release-tag.yaml
Ensure release tags generated in ci are signed.
=> ci: sign bot user commits

.goreleaser.yaml
Updates checklist to include validating docs PR
=> ci: update release checklist

distributions/README.md
- Remove TODO that was already addressed in #263 
- Add some newlines into install script for easier readability
=> docs: remove todo

README.md, distributions/README.md, distributions/TROUBLESHOOTING.md, distributions/nrdot-collector-host/README.md, distributions/nrdot-collector-host/TROUBLESHOOTING.md, distributions/nrdot-collector-k8s/TROUBLESHOOTING.md
- Add general and distro-specific troubleshooting docs
=> docs: add troubleshooting guide

cmd/goreleaser/internal/configure.go, distributions/nrdot-collector-host/.goreleaser-nightly.yaml, distributions/nrdot-collector-host/.goreleaser.yaml, distributions/nrdot-collector-k8s/.goreleaser-nightly.yaml, distributions/nrdot-collector-k8s/.goreleaser.yaml
- Add default collector configs to archives that are currently still missing
=> fix: add missing configs to archive

distributions/README.md, distributions/TROUBLESHOOTING.md, distributions/nrdot-collector-host/README.md, distributions/nrdot-collector-host/TROUBLESHOOTING.md, distributions/nrdot-collector-k8s/README.md, distributions/nrdot-collector-k8s/TROUBLESHOOTING.md, scripts/get-version.sh
- Add installation instructions to docs
- Add script to ensure version consistency of referenced version in docs
=> docs: adapt install script for rpm

distributions/README.md, distributions/nrdot-collector-host/manifest.yaml, distributions/nrdot-collector-k8s/manifest.yaml, scripts/bump-component-versions.sh, scripts/bump-nrdot-version.sh
- Bump version to 1.0.1
- Add nrdot bump script
- Fix component bump script to avoid sed creating extra files
=> chore: bump nrdot to 1.0.1

.gitignore, test/charts/nr_backend/templates/daemonset.yaml, test/charts/nr_backend/templates/deployment-collector.yaml, test/charts/nr_backend/values.yaml, test/terraform/nightly/main.tf
Adding demo service to nightly
=> ci: add demo service in nightly as sidecar

.github/actions/gh-metrics.js, .github/workflows/report-metrics.yaml
Fetches GH release download stats and reports them to NR every 2 hours.
=> ci: report GH download count metrics to NR

distributions/nrdot-collector-k8s/config-daemonset.yaml, distributions/nrdot-collector-k8s/config-deployment.yaml, distributions/nrdot-collector-k8s/sync-configs.sh
- Sync config from nr-k8s-otel-collector:0.8.7
- Config changes are related to fine-tuning of ingested metrics to reduce ingest bytes and cardinality
- Add definition for (unused) debugexporter for consistent troubleshooting experience
=> feat: sync k8s config with helm chart

distributions/README.md, distributions/nrdot-collector-host/manifest.yaml, distributions/nrdot-collector-k8s/manifest.yaml, scripts/bump-nrdot-version.sh
- Bumping minor version due to new component (routingconnector) #305
=> chore: bump to 1.1.0

distributions/nrdot-collector-k8s/config-deployment.yaml
- Sync changes from [this PR](https://github.com/newrelic/helm-charts/pull/1708)
=> feat: sync k8s config with helm chart v0.8.13

.github/workflows/ci-bump-component-versions.yaml, scripts/bump-component-versions.sh
Check if there are new upstream otel component versions and pull a pr if necessary.
=> ci: update otel components on cron

test/terraform/nightly/main.tf
=> test: fix nightly spec parsing

distributions/README.md, distributions/nrdot-collector-host/manifest.yaml, distributions/nrdot-collector-k8s/manifest.yaml, distributions/nrdot-collector/manifest.yaml, scripts/bump-nrdot-version.sh
- Prep minor release to publish #386
=> chore: prep release 1.5.0
