- distributions/nr-otel-collector/Dockerfile
- distributions/nr-otel-collector/nr-otel-collector.conf
It disables the `pkg.translator.prometheus.NormalizeName` feature-gate by default.
The feature gate was enabled by default by [reaching the beta state](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20519/files#diff-29db204fdb7feae902a4f6e8e034f2b00d5c515960dfdd124b6e85eb26d81b1eL87) in otelcollector-contrib [v0.76.3](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.76.3). When this feature-gate is enabled prometheus metrics names are renamed to match OTEL conventions [in the prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a619329714c5ca24b0e9ba2a83025c441cbf35a8/receiver/prometheusreceiver/internal/metricfamily.go#L305) and we would like to avoid this behavior by default.
Additionally, …
> [NR-120689] disable prometheus normalization feature-gate by default

- configs/README.md
- configs/nr-otel-collector-agent-linux.yaml
- distributions/nr-otel-collector/nr-otel-collector.conf
- test/canaries/templates/nr-otel-collector-agent.yml.j2
Optimizations:
* Reduce collection interval to default 60s
* Disable process metrics to align with NRI defaults
* Add cumulativetodelta processor to align with New Relic OTLP preferences
* Drop metric description and unit 
Separate cleanup including:
* Use otlphttp exporter instead of otlp to align with New Relic OTLP preferences
* Split out dedicated pipelines for host metrics and logs
Corresponding synchronization PR in `newrelic-opentelemetry-examples`: https://github.com/newrelic/newrelic-opentelemetry-examples/pull/636
cc @alanwest
> Optimize and align host monitoring config with newrelic-opentelemetry-examples

- test/canaries/alerts/vars.auto.tfvars.dist
Latest release `0.8.0` triggered the network packet receive/transmit alert for some of the canaries. I didn't found any relevant data on the receiver changelog, and metrics looked to be working Ok so increasing the threshold to avoid new false positive.
> chore: increase threshold of network packet alert on canary

- .github/workflows/clean_test_infra_on_demand.yml
- Add workflow to destroy packaging and canary testing infrastructure, i.e. EC2 instances launched by terraform scripts, on demand.
- Boolean flag allows destroying only canary or packaging infra. This can be helpful when canary tests were started on demand while the packaging tests were still failing and we don't want to interfere with those parallelized test strains.
- [Prerelease workflow for 0.8.3](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11300063884) fails repeatedly for the same reason. In order to rule out the reused EC2 instance as the culprit, we should have a workflow to reset test infrastructure on demand.
- Having this workflow allows maintainers to debug broken workflows without having to have write access to the underlying AWS test account
> ci: add workflow to reset stateful test infra

- .github/workflows/clean_test_infra_on_demand.yml
- Fixing [missing permission](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11465545111/job/31904219825) for delete workflow
> Add permissions to delete workflow

- test/provision/terraform/caos-linux.auto.tfvars.dist
We're seeing spurious failures while provisioning some of the ec2 instances, we're reducing the scope for now while we iron out the details of what os/arch we need to be testing for.
> chore: Remove all but ubuntu instances in test pipeline

- distributions/nr-otel-collector/manifest.yaml
`0.8.4` was cut without a version bump associated so we're bumping the release to `0.8.5`
> release 0.8.5

- .github/workflows/ci-prerelease.yml
- .github/workflows/component_canaries.yml
- No longer supply PREVIOUS_TAG in prerelease workflow and default to empty string instead so that [set_versions.sh](https://github.com/newrelic/opentelemetry-collector-releases/blob/b3e88ea15f7fb80d9116cd36f5c53643c9f46aeb/.github/workflows/scripts/set_version.sh#L13) can infer the previous tag as using `latest` always leads to [an error](https://github.com/newrelic/opentelemetry-collector-releases/blob/b3e88ea15f7fb80d9116cd36f5c53643c9f46aeb/.github/workflows/scripts/set_version.sh#L32), see example [from 0.8.5 prerelease](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11507504187/job/32085605669#step:5:17).
- For any situation out of the ordinary (inferred previous tag isn't the one we want to compare with), we can always destroy canaries and alerts with on …
> fix: infer previous tag during prerelease workflow

- test/canaries/alerts/vars.auto.tfvars.dist
- Goal is to make canary alerts going off a more reliable signal prompting actual investigation instead of just confirming false positives. We'll do this by adjusting alerting thresholds to account for volatile signals and thus inherent discrepancies between the previous/current canaries scraping the same host metrics as the scraping will not be perfectly aligned.
- In order to make an informed decision about more appropriate thresholds, I analyzed alerts going off for the latest canary iteration.
- [Alerts in stable state (post deployment) of canaries 0.8.5 vs 0.8.4](https://staging.onenr.io/02wdvL5p9jE) (for reference [including startup](https://staging.onenr.io/08woXpvb5Rx))
- For reference [scrape frequency is 20s](https://github.com/newrelic/opentelemetry-collector-releases/blob/e09d0 …
> fix: Adjust canary alerting thresholds

- SECURITY.md
- Replaces https://github.com/newrelic/opentelemetry-collector-releases/pull/126 as I couldn't rebase that fork to make it pass tests.
- Removing the SECURITY.md [should](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) just lead to us defaulting to the default one for the newrelic org.
> chore: delete SECURITY.md to use org default

- distributions/nr-otel-collector/THIRD_PARTY_NOTICES.md
- distributions/nr-otel-collector/manifest.yaml
Per the [docs](https://pkg.go.dev/go.opentelemetry.io/collector/extension/ballastextension#section-readme) this component has been deprecated in favor of using the `GOMEMLIMIT` envvar.  It's no longer present as of `0.109.0` https://github.com/open-telemetry/opentelemetry-collector/tree/v0.109.0/extension
Currently our helm-charts do not appear to be exposing this config so there should be no issue dropping it: https://github.com/search?q=repo%3Anewrelic%2Fhelm-charts%20memory_ballast&type=code
> chore: Removing deprecated ballastextension component

- .github/workflows/ci.yaml
- .github/workflows/component_snyk.yml
- .github/workflows/component_trivy.yml
- .github/workflows/download_trivy_db.yml
- .github/workflows/security.yml
- Trying to address the GHCR global rate limiting issue ([that affects all users of trivy b/c its a ratelimit on the vendor namespace](https://github.com/orgs/community/discussions/139074)) by combining all of the available fixes, i.e.
1. Use [oras](https://oras.land/) to [download trivy db only once daily and cache in workspace](https://github.com/aquasecurity/trivy-action/issues/389#issuecomment-2373539982). 
2. Modified `oras pull ghcr.io/aquasecurity/trivy-db:2` to `{ oras pull ghcr.io/aquasecurity/trivy-db:2 } || { oras pull public.ecr.aws/aquasecurity/trivy-db:2 }` (same for java db download) to enable a fallback to ECR which [also hosts the db](https://github.com/aquasecurity/trivy-action/issues/389#issuecomment-2373539982) but can also be affected by ratelimiting.
- Changed …
> fix: download trivy db only once per day

- .github/CODEOWNERS
Changing codeowners to new owning team [otelcomm](https://github.com/orgs/newrelic/teams/otelcomm)
> chore: Change codeowners to otelcomm

- .github/workflows/component_trivy.yml
- Changing trivy workflow from split logic based on 'scheduled or not' to 'scanning latest or not'. If we're scanning latest, it can upload the results even if we run it manually. This will hopefully allow us to get to the bottom of why the [scheduled scan failed](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11744528669/job/32719848741) while the  [manually triggered one](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11728764538) succeeded.
- Removing checkout because the manual run didn't have it and we are just scanning an image that is published to docker hub and we're not using any local config file like some of the [docs](https://github.com/aquasecurity/trivy-action) suggest, so there should be no reason to checkout the repo. …
> chore: simplify trivy workflow for easier debug

- .github/workflows/component_trivy.yml
- In order to not skip the print/upload step on a trivy failure, we need to prepend a status check expression, otherwise it defaults to `success()` only ([see docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#failure-with-conditions))
- Added `inputs.tag == 'latest'` conditional to slack step as other tags would only be present in manual runs and we can save us the notification in that case
> chore: print and upload trivy results also on fail

- .github/workflows/component_trivy.yml
- #151 fixed the security workflow so that trivy now runs and [prints failure reports](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11803631347/job/32882015483) properly. Before addressing the fact that it reports 'low' priority CVE even though it's configured not to do so, I wanted to use this opportunity to fix the slack hook cause it's currently not posting messages to the slack channel.
- Based on the docs, it looks like the webhook we received from IT (`https://hooks.slack.com/services/...`) is an [incoming webhook](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-3-slack-incoming-webhook) instead of a [workflow webhook](https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-1-slack-workflow-builder), so …
> fix: Change webhook type to incoming webhook

- .github/workflows/component_trivy.yml
- Turns out sarif format does not respect the `severity` parameter unless you explicitly configure it, see [update in this message](https://github.com/aquasecurity/trivy-action/issues/309#issuecomment-2057669566) and the [official input docs](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#inputs):
>limit-severities-for-sarif: By default SARIF format enforces output of all vulnerabilities regardless of configured severities. To override this behavior set this parameter to true
> fix: exclude <= medium severity from sarif output

- .github/workflows/component_terraform.yml
- https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/11919554058 fails due to `execute_$cmd` bools not supplied. As we already supply a default, we can just make them non-required
> fix: make execute bools non-required

- distributions/nr-otel-collector/manifest.yaml
Dummy release for #158  to have a dedicated dummy commit in `main` that can be tagged with tag name adhering to semver.
> chore: dummy 0.8.6 release to move to semver tags

- distributions/nr-otel-collector/manifest.yaml
Dummy release for #158  to have a dedicated dummy commit in `main` that can be tagged with tag name adhering to semver.
Merge #159 first
> chore: dummy 0.8.7 release to move to semver tags

- .github/workflows/ci_nightly.yaml
- Build step was missing from nightly build [causing goreleaser to fail](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/12362541149/job/34502061604) as it expects source files to be present
- Renamed action as it was still using the normal CI name
> ci: fix missing build step in nightly CI

- distributions/nr-otel-collector/manifest.yaml
- Directive seems to be no longer necessary. Based on the [linked issue](https://github.com/google/gnostic/issues/262), if it was still necessary, `go get -u` would fail but it didn't when executing it locally and also the dependency is no longer mentioned in the `go.mod`, so I assume it just is no longer a transitive dependency.
> chore: remove unused gnostic replace directive

- .github/workflows/ci.yaml
- [Dependabot PR](https://github.com/newrelic/opentelemetry-collector-releases/pull/167) failed [due to missing secrets](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/12362465283/job/34501827930?pr=167) for the new terraform workflow. This is expected as dependabot PRs don't and shouldn't have access to secrets as a malicious dependency upgrade could leak those in certain language ecosystems (more details [here](https://github.com/dependabot/dependabot-core/issues/3253)). There are ways to remedy this by introducing a more complex dependabot workflow but until we actually have need for this complexity, it seems more appropriate to just skip the terraform plan of our CI.
If dependabot creates a PR for terraform resources, we can locally do a plan instead where …
> ci: skip terraform workflow for dependabot

- test/terraform/modules/eks_cluster/main.tf
- test/terraform/modules/eks_cluster/outputs.tf
- test/terraform/modules/eks_cluster/vars.tf
- test/terraform/permanent/main.tf
- test/terraform/permanent/providers.tf
Adds a permanent test cluster for deploying nightly builds.   Out of the gates we'll just use a single linux node group and eventually build out what we need longer term.  I'll have a followup pr shortly to add a simple helm release.
Should be able to pull an auth token for the cluster via:
```
data "aws_eks_cluster_auth" "this" {
name = module.ci_e2e_cluster.cluster_name
}
> feat: Adding provisioning of permanent EKS test cluster

- .github/workflows/ci.yaml
- .github/workflows/component_terraform.yml
- test/terraform/permanent/main.tf
- test/terraform/permanent/providers.tf
- test/terraform/permanent/vars.tf
Deploys our test helm-chart into the permanent eks cluster.  Currently it will just pull the most latest image until we add a test repository and/or publish nightly builds.
> feat: Deploy permanent backend into test cluster

- test/terraform/permanent/main.tf
Need to add the flag to ensure the namespace is created.  Additionally i updated it to just `nightly` for now since the use cse of the cluster can be inferred from the cluster name.
> fix: Ensure helm creates the nightly namespace

- test/terraform/modules/eks_cluster/outputs.tf
- test/terraform/permanent/main.tf
Provisions a private ECR repo and assigns read-access to the test cluster arn using the aws tf [module](https://registry.terraform.io/modules/terraform-aws-modules/ecr/aws/latest).  A followup pr will add publishing of the nightly build.
> feat: Provision ECR for test builds

- test/terraform/permanent/main.tf
Updates tf to resolve the actual resource provisioning source iam role arn rather than the sts assumed role.
> fix: Use source role for ecr access

- .github/workflows/ci-prerelease.yml
- .github/workflows/ci-prerelease_linux_on_demand.yml
- .github/workflows/ci.yaml
- .github/workflows/ci_nightly.yaml
- .goreleaser-nightly.yaml
- internal/tools/go.mod
- scripts/build.sh
- test/e2e/Makefile
- Updates golang to `1.23` to be consistent with the otel distros
- Updates goreleaser to v2 with minor changes to cli arguments
- Adds a new goreleaser config file for nightly builds (this is a temporary step until we we get a pro license setup)
- Additional steps to the nightly ci workflow to publish to ECR.  We'll need a followup pr to publish additional artifacts to s3 for the bare metals tests as well.
> Publish nightly build to ECR

- .github/workflows/ci_nightly.yaml
- .goreleaser-nightly.yaml
- test/terraform/permanent/main.tf
- We weren't passing in the ECR repo value to goreleaser, that is now solved via envvar
- Updating ECR to allow mutability until we get the publishing all ironed out
- Adding a simple `nightly` tag
> Add missing ECR registry url

- .goreleaser-nightly.yaml
- test/terraform/permanent/main.tf
- Renames the build artifact s3 bucket to something more generic: `nr-releases`
- Updates blob path to: `nr-releases/opentelemetry-collector-releases/{{ .Tag }}`
- Published binaries on nightly build
> chore: Update nightly goreleaser config to include blobs

- test/terraform/permanent/main.tf
- test/terraform/permanent/outputs.tf
As we create new distros we'll want separate ECRs, this should create a repo for each subfolder of `./distributions`
> chore: Create ECR repos on a per distro basis

- test/e2e/util/chart/nr_backend.go
- test/terraform/permanent/vars.tf
- Use `nightly` host name prefix for EKS nodes. Still using `permanent` which causes [nightly tests to fail](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/12914171239/job/36013128738#step:14:43).
- Replace `k8s-node` with `k8s_node` for consistency in regular ci tests
- [Current host names](https://onenr.io/0OwvdMG2yjv) reported to NR for reference
> ci: enforce node-naming conventions

- .github/workflows/ci-prerelease.yml
- Fixes [failing prerelease of 0.8.8](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/12936144401/job/36081079822#step:9:23) by following [goreleaser upgrade docs](https://goreleaser.com/deprecations/#-rm-dist)
> ci: use v2 goreleaser args for prerelease

- distributions/nr-otel-collector/manifest.yaml
- Release of 0.8.8 failed, fixed in #196
> chore: prepare release 0.8.9

- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- Disable nightly tests for `system.paging.usage` for EC2s until we have a better understanding on why the metrics stopped reporting. Most likely a test setup issue.
> fix: skip nightly EC2 tests for paging.usage

- test/charts/mocked_backend/Chart.yaml
- test/charts/mocked_backend/templates/daemonset.yaml
- test/charts/mocked_backend/values.yaml
- test/charts/nr_backend/Chart.yaml
- test/charts/nr_backend/templates/daemonset.yaml
- test/e2e/Makefile
- test/e2e/util/chart/mocked_backend.go
- test/e2e/util/chart/nr_backend.go
- test/e2e/util/env/env.go
- test/e2e/util/k8s/k8s.go
- test/e2e/util/test/hostname.go
- Generalize fast and slow tests to support running with a second distro published under the name `newrelic/$distro_name`.
- Nightly will be adjusted in a separate PR which will also generalize the hostname to incorporate the distro to avoid unintended overlap in queries. Post this PR this is technically the case for `slow` tests but as we still have only one distro, this is okay as a temporary state and can be addressed in the follow-up PR.
- Tested by locally modifying `.goreleaser.yaml` to publish docker images to `newrelic/foobar` and running makefile with`DISTRO=foobar`.
- Running fast tests for two distros at the same time was successful
> ci: support distro-dependent tests

- distributions/nr-otel-collector/test-spec.yaml
- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- test/e2e/util/chart/chart.go
- test/e2e/util/chart/mocked_backend.go
- test/e2e/util/spec/nightly.go
- test/e2e/util/spec/on_host.go
- test/e2e/util/spec/specfile.go
- test/e2e/util/test/hostname.go
- test/e2e/util/test/path.go
- test/terraform/modules/ec2/main.tf
- test/terraform/modules/ec2/vars.tf
- test/terraform/permanent/main.tf
- Introduce per-distro `test-spec.yaml` to toggle nightly tests. The idea was that this could be a starting point to also incorporate features like skipping specific metrics and/or listing the metrics to test in the first place.
- Corresponding nightly test infra is only deployed when enabled, e.g. `k8s` distro will not need to run on bare EC2s, so the EC2s shouldn't be deployed in the first place.
- Skipped toggling k8s_node tests for now as both `host` and `k8s` will need to support it and when we move to testing `k8s` in host/gateway mode, we'll need to provide more finegrained control at which point we can incorporate skipping parts of it for the `host` distro
- Incorporate distro into
- k8s namespace to minimize interference
- the hostname to 'namespace' data in NR
- [tf …
> ci: support skip nightly tests by distro/host

- test/terraform/modules/ec2/main.tf
- Fix [name conflicts](https://github.com/newrelic/opentelemetry-collector-releases/actions/runs/13018479919/job/36313392156#step:6:1394) for EC2 resources caused by #201
> ci: namespace EC2 resources

- test/terraform/modules/ec2/main.tf
- Downloading `deb` package from S3 on EC2s fails as `latest_deb_package_filename` expression also matches the checksum files and files from older versions. Adding a `$` anchor filters out the checksum/signature files and `head` filters out older versions.
- Also added a grep for the collector distro as that will also result in non-unique results
> ci: fix EC2 install script

- test/e2e/util/test/hostname.go
- Reverting the 'normalization' of the distro in the host name as it causes nightly to fail. I initially thought it would be worth for readability but it also forces normalizing it in terraform which just becomes cumbersome to remember. If readability becomes an issue, adopting a different separator than `-` might be preferable than trying to shoehorn all segments that naturally contain hyphens into using a different character.
> ci: revert normalizing host.name in query

- .github/workflows/ci.yaml
- Makefile
- Makefile.dev
- README.md
- cmd/goreleaser/internal/configure.go
- distributions/README.md
- distributions/nr-otel-collector/Makefile
- distributions/nr-otel-collector/README.md
- distributions/nr-otel-collector/config.yaml
- distributions/nr-otel-collector/manifest.yaml
- distributions/nrdot-collector-host/.goreleaser-nightly.yaml
- distributions/nrdot-collector-host/.goreleaser.yaml
- distributions/nrdot-collector-host/Dockerfile
- distributions/nrdot-collector-host/README.md
- distributions/nrdot-collector-host/THIRD_PARTY_NOTICES.md
- distributions/nrdot-collector-host/config.yaml
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-host/nrdot-collector-host.conf
- distributions/nrdot-collector-host/nrdot-collector-host.service
- distributions/nrdot-collector-host/postinstall.sh
- distributions/nrdot-collector-host/preinstall.sh
- distributions/nrdot-collector-host/preremove.sh
- distributions/nrdot-collector-host/test-spec.yaml
- test/terraform/permanent/main.tf
- test/terraform/permanent/outputs.tf
- Added host distro named `nrdot-collector-host`. Files are copied from `nr-otel-collector` and modified as necessary:
- Removed feature gate (`--feature-gates=-pkg.translator.prometheus.NormalizeName`) from default args (Dockerfile and `.conf` file) as distro does not contain [prometheus-related components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/README.md#full-normalization)
- Removed ports `55678` and `55679` from docker `EXPOSE` as they are related to [OpenCensus](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/opencensusreceiver#getting-started) which we do not use
- Bumped provider versions to `1.24.0` to match component version of `0.118.0` (see [otel release …
> feat: add nrdot-collector-host distro

- test/terraform/modules/ec2/main.tf
Updates the ec2 test instances to pull from the `nrdot-collector-releases` base key
> fix: Update s3 bucket name

- distributions/nr-otel-collector/manifest.yaml
- distributions/nr-otel-collector/nr-otel-collector.service
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/manifest.yaml
- It appears that the `description` field gets incorporated into the user agent header (instead of the `name`) that the collector adds when sending telemetry to NR.  In order to allow facetting ingest data by distro, we should ensure that the description also contains the distro name. I chose an arbitrary distro name `Legacy` for `nr-otel-collector` so that we can use a single pattern to parse the distro.
> feat: add distro to user agent

- test/terraform/modules/ec2/main.tf
- Incorporate [missing distro name](https://github.com/newrelic/opentelemetry-collector-releases/blob/50b9f03b0430803fce4e726a9463dc6d2d8c2f46/distributions/nrdot-collector-host/.goreleaser-nightly.yaml#L121) into s3 path when querying for binaries in EC2 on startup
> fix: add missing distro folder/namespace to s3 path

- .github/workflows/release-draft.yaml
- .goreleaser.yaml
- cmd/goreleaser/internal/configure.go
- distributions/nrdot-collector-host/.goreleaser-nightly.yaml
- distributions/nrdot-collector-host/.goreleaser.yaml
- distributions/nrdot-collector-k8s/.goreleaser-nightly.yaml
- distributions/nrdot-collector-k8s/.goreleaser.yaml
Adds a new workflow to generate a draft release on tag push.
1. Build and publish each distro via their respective .goreleaser.yaml configs.  They will publish docker images to ECR for now and append or create a new draft release in GH as well as upload all of their generated artifacts.
2. Run goreleaser on the root config which will populate the draft with the changes included since last release.
A followup PR is going to be required to handle the publishing of the release, this will also need to push and tag images to docker hub.
> feat: Add workflow for drafting releases

- test/e2e/util/spec/on_host.go
- Nightly [fails](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13401218903/job/37432282013#step:17:92) due to new requirement of cpu util for `state=steal` but it's [just 0](https://onenr.io/0PwJ943M5Q7) which is fine as far as I understand the metric
> fix: relax condition on steal metric

- .github/workflows/ci-nightly.yaml
- Namespacing clusters used for nightly slow tests to avoid interference between tests of different distros
> fix: namespace kind clusters used for slow tests

- test/e2e/hostmetrics_slow/hostmetrics_slow_test.go
- test/e2e/util/chart/nr_backend.go
- the slow test didn't supply a namespace value, leaving the ClusterRole with the (wrong) default namespace name, leading to [permissions issues for nightly](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13403283329/job/37438427097#step:17:444)
> fix: override namespace of clusterrole

- Makefile
- scripts/get-version.sh
Adding a helper target for generating new release tag along with basic version validation across the distros.
> feat: Add release tag helper and version validation

- .github/workflows/ci-nightly.yaml
- distributions/README.md
- distributions/nrdot-collector-host/config.yaml
- distributions/nrdot-collector-host/nrdot-collector-host.conf
- Supply env var defaults via config instead of systemd config to also provide defaults when used as docker image
- Dropped the port for simplicity as 443 supports both gRPC and http, see [NR docs](https://docs.newrelic.com/docs/opentelemetry/best-practices/opentelemetry-otlp/#note-ports). As far as I can tell, the old systemd default port was also wrong as it was for gRPC while the config used the otlphttpexporter
> feat: provide env var defaults for docker

- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- test/e2e/hostmetrics_slow/hostmetrics_slow_test.go
- test/e2e/util/assert/nr_metric_assertion.go
- Nightly run [failed due to missing metric](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13419200827/job/37487529735#step:17:105) but metric [did get ingested](https://onenr.io/02wdo549GQE), so I assume it's a race condition. Adding some retry behavior to not immediately fail but account for variable ingest delay
> fix: retry NR backend validations

- test/terraform/nightly/main.tf
- fix [remnant](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13419200827/job/37493600871#step:6:102) of refactoring that happened during #218 - tf used to handle all distros instead of namespacing it via workspaces. ecr data construct now uniquely identifies a distro's repo, so no need for indexing.
> fix: avoid use of index when reading ecr

- .github/workflows/release-draft.yaml
- cmd/goreleaser/internal/configure.go
- distributions/nrdot-collector-host/.goreleaser-nightly.yaml
- distributions/nrdot-collector-host/.goreleaser.yaml
- distributions/nrdot-collector-k8s/.goreleaser-nightly.yaml
- distributions/nrdot-collector-k8s/.goreleaser.yaml
Looks like the parallel builds can create a race condition when attempting to post the draft, moving things around to ensure the draft is already present when they start.
> fix: Issue with race condition while publishing draft

- test/charts/mocked_backend/templates/k8s-api-access.yaml
- test/charts/nr_backend/templates/k8s-api-access.yaml
- tf nightly apply failed due to the [non-namespaced](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1/) `ClusterRole` running into conflicts.
- Adding `meta.namespace` wouldn't have helped if I understand [the docs](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta) correctly as `ClusterRole` falls into
> Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
> fix: namespace cluster roles for multi chart install

- cmd/goreleaser/internal/configure.go
- distributions/nrdot-collector-k8s/.goreleaser-nightly.yaml
- distributions/nrdot-collector-k8s/.goreleaser.yaml
By default it looks like the binaries are built into an archive file so in order to ensure the name matches the distro we need to keep the config: https://goreleaser.com/customization/archive/?h=archives#archives
> fix: Add archive option to k8s distro

- test/terraform/nightly/providers.tf
- State name now uses the new repo name and the correct folder name for namespacing
> ci: use correct repo and tf project name for state

- test/charts/mocked_backend/templates/k8s-api-access.yaml
- test/charts/mocked_backend/values.yaml
- test/charts/nr_backend/templates/k8s-api-access.yaml
- test/charts/nr_backend/values.yaml
- test/e2e/hostmetrics/hostmetrics_test.go
- test/e2e/hostmetrics_slow/hostmetrics_slow_test.go
- test/e2e/util/chart/mocked_backend.go
- test/e2e/util/chart/nr_backend.go
- test/terraform/nightly/main.tf
- `namespace` value is missing from nightly helm chart
> fix: provide namespace for clusterrole in nightly

- .github/workflows/ci-nightly.yaml
- Having nightly apply the tf for each distro concurrently causes deadlocks in dynamoDB and state corruption when one tf fails and kills the other one.
- Following [github docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-concurrency-and-the-default-behavior) using concurrency groups to limit concurrency to 1
> ci: limit concurrency of nightly tf

- .github/workflows/ci-nightly.yaml
- goreleaser nightly publish step was missing an `id` to extract the artifacts
> ci: add label to goreleaser publish step

- .actrc
- .github/workflows/ci-nightly.yaml
- .github/workflows/terraform.yaml
- test/e2e/Makefile
- enable artifact support with act ([docs](https://nektosact.com/usage/index.html#action-artifacts))
- pass manifest sha [via artifacts](https://github.com/actions/runner/pull/2477#issuecomment-2037465490) as dynamic output variables are [not supported](https://github.com/actions/runner/pull/2477)  and nightly helm apply [failed for k8s](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13466079899/job/37632896387#step:7:472) b/c it was using the sha of the host distro due to race condition
- add missing checkout to nightly tests as it was split into a different job in a previous PR
> ci: correctly pass docker manifest sha to tf

- .github/workflows/release-tag.yaml
Adds a workflow that will create a tag in the event a version without a tag is pushed
> ci: add release tag workflow

- .github/workflows/release-tag.yaml
We need to use a PAT in order to trigger a workflow from a workflow: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
> ci: add release token for tagging

- .github/workflows/release-draft.yaml
- .github/workflows/release-publish.yaml
- .github/workflows/release-tag.yaml
- .goreleaser.yaml
Add a new workflow to handle publishing releases.
Once a release is published we will copy the manifest using [imagetools](https://docs.docker.com/reference/cli/docker/buildx/imagetools/create/) from ECR to DockerHub.  Eventually we will cut this step out and simple tag the existing version with `latest`.
Additionally this adds a basic checklist to our release drafts.
> ci: add release publish workflow

- Makefile
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/manifest.yaml
- scripts/bump-versions.sh
Added a helper script until we configure rennovate to ensure we're using the correct versions of contrib/core as well as updated our components to 1.20.0
> chore: Updating otel components

- .github/workflows/ci-base.yaml
- .github/workflows/ci-nightly.yaml
- .github/workflows/ci.yaml
- [Nightly failed](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13546938296/job/37860805144#step:14:31) due to cluster name being too long when I added the run-id + attempt, so removing unnecessary prefixes to hopefully make it work. Most likely limit we're hitting [is 63](https://stackoverflow.com/a/28918017) (couldn't find anything official from kind/docker) as the [docker run](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13546938296/job/37860805144#step:14:38) with hostname `ci-e2etest-nightly-nrdot-collector-host-13546938296-1-control-plane` failed (67 chars).
> ci: use shorter cluster names compatible with kind

- test/terraform/nightly/main.tf
- fix [nightly error](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13550502544/job/37873982667#step:8:171)
> ci: enable helm dependency update for nightly

- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- test/e2e/hostmetrics_slow/hostmetrics_slow_test.go
- With query retry in place, we no longer need to artificially space out requests and can instead just run into the rate limit and retry to keep it simple. It also speeds up nightly tests a lot (1min vs 5s locally)
- This should help identify the root cause of [nightly timing out](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13572948183/job/37943719544#step:4:32)
> test: remove request spacing behavior in tests

- test/charts/mocked_backend/templates/daemonset.yaml
- test/charts/nr_backend/templates/daemonset.yaml
- Fixes that the helm conditionals for the k8s cluster unintentionally also messed up the host name for the host distro.
- Also add conditionals for k8s-only env vars for the mock_backend chart
> ci: fix host.name for host distro in nr_backend

- .github/workflows/security.yaml
- full image name contained a `/` causing trivy [failing to write the sarif file](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13597629278/job/38017906425#step:2:170)
> ci: fix security check

- test/terraform/nightly/main.tf
- Set clustername for nightly helm chart to avoid default cluster name
> ci: set cluster name for nightly collectors

- distributions/nrdot-collector-host/README.md
- distributions/nrdot-collector-k8s/README.md
In order to indicate that some distros will have differing stability we're opting to note their state in the respective readme files.
> docs: flagging k8s distro as preview

- distributions/nrdot-collector-host/config.yaml
- The [debugexporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md) is intended for debugging purposes and shouldn't be enabled by default
> feat: remove debug exporter from default host config

- test/terraform/modules/eks_cluster/main.tf
- Reduce cost by limiting cloudwatch retention for the EKS cluster. We don't really use the logs, so reduced it to 1d in case we want to debug something live.
> ci: reduce cloudwatch retention for eks to 1d

- .github/workflows/release-publish.yaml
Updates the release notes PR to use the current username rather than the generic github actions user.  This allows local users to still run the workflow with their tokens.
> ci: update publish notes pr username

- test/charts/nr_backend/templates/daemonset.yaml
- Remove unnecessary `initContainers` for nr_backend chart as it does not contain the validation backend - was accidentally copied from mock-backend
> chore: remove unnecessary init container

- .github/workflows/release-publish.yaml
- Double quotes unintentional [caused shell interpretation](https://github.com/newrelic/nrdot-collector-releases/actions/runs/13931159464/job/38988358850#step:5:41) of backtick quoted changelogs.
> ci: prevent bash interpretation of docs

- .github/workflows/ci-nightly.yaml
- Makefile
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/manifest.yaml
- distributions/nrdot-collector-k8s/test-spec.yaml
- scripts/get-version.sh
- test/e2e/Makefile
- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- test/e2e/hostmetrics_slow/hostmetrics_slow_test.go
- test/e2e/util/spec/test_spec.go
- test/e2e/util/spec/test_spec_test.go
- test/e2e/util/spec/testdata/test-spec-with-where.yaml
- test/e2e/util/spec/testdata/test-spec-without-where.yaml
Allows for overriding test spec where clause per distro to account for differences in configs, particularly k8s dropping the resourcedetection/ env config.  Also updates otel components to the latest patch version.
> ci: remove host from slow test where clause

- Makefile
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/manifest.yaml
Bumping components to `0.123.0`, should address the CVE from https://github.com/newrelic/nrdot-collector-releases/pull/291
> feat: bumping otel components to 0.123.0

- test/e2e/hostmetrics_nightly/hostmetrics_nightly_test.go
- test/e2e/util/spec/host.yaml
- test/terraform/modules/ec2/main.tf
- Remove `system.paging.usage` tests as maintaining testing infra to reliably emit this metric turns out to be too much effort
> test: remove system.paging.usage tests

- distributions/nrdot-collector-host/config.yaml
- Implementing best practices for batchprocessor and memorylimiterprocessor
- [batch](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.124.0/processor/batchprocessor) should be after memory and any dropping processor. This is the case for both distros as it's the last processor in all pipelines
> It is highly recommended to configure the batch processor on every collector. The batch processor should be defined in the pipeline after the memory_limiter as well as any sampling processors. This is because batching should happen after any data drops such as sampling.
- [memorylimiter](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.124.0/processor/memorylimiterprocessor#best-practices) should be first for all pipelines
- k8s distro was fixed upstream in [this …
> feat: configure memory_limiter for all pipelines

- README.md
- distributions/core-components.md
- distributions/nrdot-collector-host/THIRD_PARTY_NOTICES.md
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/THIRD_PARTY_NOTICES.md
- distributions/nrdot-collector-k8s/manifest.yaml
To enhance customizability of the OTel connector configs/pipelines we want to introduce the connector component to the K8s Helm chart. In order to do so, we need NRDOT to support connectors.
[Relevant Jira Ticket](https://new-relic.atlassian.net/browse/NR-383421)
> Add the routing connector to the K8s NRDOT distro

- .github/workflows/lint-conventional-commits.yaml
- Simple workflow to validate PR title to avoid the suggested commit message to not adhere to conventional commits and therefore end up excluded from the auto-generated changelogs in the draft release.
- If it fails, it comments (like [here](https://github.com/newrelic/nrdot-collector-releases/pull/307#issuecomment-2855943630) when I removed the `ci:` prefix from the title) and fails the workflow
> ci: ensure conventional commit PR title

- .github/workflows/ci-snapshot-cli.yaml
- cmd/nrdot-collector-builder/.goreleaser.yaml
- cmd/nrdot-collector-builder/Dockerfile
- cmd/nrdot-collector-builder/cmd/manifest/update.go
- cmd/nrdot-collector-builder/cmd/manifest/update_test.go
Adds a workflow to build and publish a snapshot of the nrdot-collector-builder to ghcr.io
Tests run but will not fail the build until stabilized
> feat: Add cli docker snapshot release

- .github/workflows/ci-snapshot-cli.yaml
Updates the cli workflow to publish docker manifests on snapshot
> chore: Ensure snapshots are pushed to registry

- cmd/nrdot-collector-builder/cmd/manifest.go
- cmd/nrdot-collector-builder/cmd/manifest/update.go
- cmd/nrdot-collector-builder/internal/manifest/config.go
- cmd/nrdot-collector-builder/internal/manifest/config_test.go
- cmd/nrdot-collector-builder/internal/manifest/main.go
- scripts/bump-component-versions.sh
Updates the builder cli to parse for beta core/contrib and stable core versions.  The also updates the version bump script to use the cli.
> feat: Ensure cli builder uses proper version of the collector

- .github/workflows/ci-bump-component-versions.yaml
Needed to fix a few things around git commits, also improved a few things:
- Handles cases where remote branch already exists
- Closes prs for older prs that are still open
- Updates pr if it already exists
Here is a link to the successful run: https://github.com/newrelic/nrdot-collector-releases/pull/316
> fix: Fix pr generation on version bump

- distributions/nrdot-collector-host/test-spec.yaml
- distributions/nrdot-collector-k8s/test-spec.yaml
- test/e2e/util/spec/k8s.yaml
- test/terraform/nightly/main.tf
- Use nr-k8s-otel-collector helm chart for nightly tests of k8s distro
- Peer PR to [this one](https://github.com/newrelic/nrdot-collector-releases/pull/325) which addresses fast and slow tests
> test: use nr-k8s-otel-collector for k8s nightly

- distributions/README.md
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/README.md
- distributions/nrdot-collector-k8s/manifest.yaml
- scripts/bump-nrdot-version.sh
- Bump version to 1.1.1
- Label `nrdot-collector-k8s` as public
> chore: release k8s distro

- .github/renovate.json5
- .github/workflows/lint-renovate-config.yaml
- distributions/nrdot-collector-k8s/test-spec.yaml
- Renovate doesn't match same regex twice per file (#334) but rather just the last one as far as I can tell, otherwise I would've expected a second PR by now.
- The best I could come up with to address this was to use yaml anchors instead. It also expresses more clearly that those versions are supposed to be the same
- Reverting it back to 0.8.28 to see if renovatebot works correctly
> chore(deps): ensure dep chart version lockstep

- .github/workflows/ci-nightly.yaml
- .gitignore
- cmd/goreleaser/internal/configure.go
- distributions/nrdot-collector-host/.goreleaser-nightly.yaml
- distributions/nrdot-collector-host/.goreleaser.yaml
- Replace references to CAOS team with OTELCOMM
- Remove secret nr_api_base_url which is no longer used by ci-base.yaml
> chore: cleanup old team references

- distributions/README.md
- distributions/nrdot-collector-host/manifest.yaml
- distributions/nrdot-collector-k8s/manifest.yaml
- distributions/nrdot-collector/manifest.yaml
- scripts/bump-nrdot-version.sh
Version bump to prep release `1.3.0`
> chore: prep release 1.3.0

- .github/workflows/ci-nightly.yaml
Missing deploy step for core distro
> chore: Add missing ec2 nightly deploy

- .github/workflows/ci-base.yaml
- .github/workflows/ci-nightly.yaml
- .github/workflows/release-draft.yaml
- [Nightly failed](https://github.com/newrelic/nrdot-collector-releases/actions/runs/17437682159/job/49513819884#step:13:24) and the only thing that seems to have changed is the goreleaser verison (2.11.2 -> 2.12.0). As the [new version has no obvious breaking change that would affect us](https://goreleaser.com/blog/goreleaser-v2.12/#attestations), this PR pins the last known working version in the hope to fix the build until we have time to investigate further.
> ci: pin goreleaser at last working version

- distributions/nrdot-collector-host/test/spec-nightly.yaml
- distributions/nrdot-collector/test/spec-nightly.yaml
- test/charts/nr_backend/Chart.yaml
- test/charts/nr_backend/templates/daemonset.yaml
- test/charts/nr_backend/values.yaml
- test/e2e/nightly/nightly_collector_nr_backend_test.go
- test/e2e/util/spec/host.yaml
- test/e2e/util/spec/nightly.go
- test/e2e/util/spec/test_case_spec_test.go
- test/terraform/modules/ec2/main.tf
- test/terraform/nightly/main.tf
- Migrates nightly to use `testKey` resource attribute to identify telemetry at query time. This is both to iterate towards using `newrelic/newrelic-integration-e2e-action` eventually but also to remove the overwrite of `host.name` in our nightly tests so that we can better verify the behavior of our resourcedetectionprocessor configs.
> test: use testKey instead of host.name for nightly

- cmd/goreleaser/internal/configure.go
- distributions/nrdot-collector-host/.goreleaser-fips.yaml
- distributions/nrdot-collector-host/.goreleaser-nightly.yaml
- distributions/nrdot-collector-k8s/.goreleaser-fips.yaml
- distributions/nrdot-collector-k8s/.goreleaser-nightly.yaml
- distributions/nrdot-collector/.goreleaser-fips.yaml
- distributions/nrdot-collector/.goreleaser-nightly.yaml
- Remove extraneous variables and methods that have no effect on the final GoReleaser files
- Create a utility function to provide a consistent source of image tags between docker images and docker manifests
- Create a common "distribution" object to clarify logic and avoid repetition
- Changes to the generated GoReleaser files:
- Create docker manifests for all images with the `:{{ .Version }}-nightly` tag to maintain consistency with the rest of the program
- ~Fixes cases where Linux archives are overridden to .zip in fips~
- Removes the archives section for fips
- Ensured there were no changes in the generated goreleaser.yaml files (aside from the changes mentioned above)
> refactor: refactor goreleaser generator

- distributions/nrdot-collector-k8s/THIRD_PARTY_NOTICES.md
- distributions/nrdot-collector-k8s/manifest.yaml
This is a very useful processor that allows us to create custom metrics on the client (Collector) side instead of from within ingest/ NRQL. 
The ability to do some simple arithmatic from the collector prevents us from having to either: 
* Create a new ingest pipeline to scrape and combine metrics upon ingest
* Create overly complicated queries. 
Take for example the following query. 
``` SQL
FROM(
FROM(
FROM Metric 
SELECT latest(kube_pod_container_resource_requests) AS containerRequest
WHERE resource = 'cpu' AND container_phase != 'terminated'
FACET k8s.container.name, k8s.pod.name, k8s.node.name, k8s.namespace.name LIMIT MAX
)
SELECT sum(containerRequest) AS totalRequests FACET k8s.node.name LIMIT MAX
) 
JOIN (
FROM Metric
SELECT latest(kube_node_status_allocatable) AS totalAllocatable …
```
> Feat: Adding metrics generation processor from opentelemetry-collector-contrib

- .github/workflows/release-draft.yaml
- .github/workflows/release-publish.yaml
Adds build/publish step for fips on draft and copies the manifest on on publish
> ci: add fips to release draft and publish
